version: '2.4'

x-app: &app
    image: "${DOCKER_REGISTRY}/mine/mine"
    shm_size: '30gb'
    working_dir: /srv
    volumes:
      - .:/srv
    runtime: nvidia
    restart: always


services:
  eth:
    <<: *app
    environment:
      - WORKER
      - ETH_POOL
      - ETH_USER
    command: miner --algo ethash --server $ETH_POOL --user $ETH_USER

  rvn:
    <<: *app
    environment:
      - WORKER
      - RVN_POOL
      - RVN_USER
    command: miner --algo kawpow --server $RVN_POOL --user $RVN_USER

  beam:
    <<: *app
    environment:
      - WORKER
      - BEAM_POOL
      - BEAM_USER
    command: miner --algo beamhash --server $BEAM_POOL --user $BEAM_USER
