version: '2.4'

x-app: &app
    image: "${DOCKER_REGISTRY}/mine/mine"
    build:
      context: .
    shm_size: '30gb'
    runtime: nvidia
    restart: always


services:
  app:
    <<: *app

  eth:
    <<: *app
    environment:
      - WORKER
      - ETH_POOL
      - ETH_USER
    command: miner --algo ethash --server $ETH_POOL --user $ETH_USER.$WORKER

  rvn:
    <<: *app
    environment:
      - WORKER
      - RVN_POOL
      - RVN_USER
    command: miner --algo kawpow --server $RVN_POOL --user $RVN_USER.$WORKER

  beam:
    <<: *app
    environment:
      - WORKER
      - BEAM_POOL
      - BEAM_USER
    command: miner --algo beamhash --server $BEAM_POOL --user $BEAM_USER.$WORKER

  chia:
    <<: *app
    entrypoint: bash chia_entrypoint.sh
    volumes:
      - ./mkplots.sh:/mkplots.sh
      - ./chia_entrypoint.sh:/chia_entrypoint.sh
      - ./chia_keys:/chia_keys
      - $TMP_PLOTS:/tmp_plots
      - $PLOTS:/plots
    environment:
      - WORKER
