version: '2.4'

x-app: &app
    image: "${DOCKER_REGISTRY}/mine/mine"
    build:
      context: .
    shm_size: '30gb'
    runtime: nvidia
    restart: always


services:
  app:
    <<: *app

  eth:
    <<: *app
    environment:
      - WORKER
      - ETH_POOL
      - ETH_USER
    command: miner --algo ethash --server $ETH_POOL --user $ETH_USER.$WORKER

  rvn:
    <<: *app
    environment:
      - WORKER
      - RVN_POOL
      - RVN_USER
    command: miner --algo kawpow --server $RVN_POOL --user $RVN_USER.$WORKER

  beam:
    <<: *app
    environment:
      - WORKER
      - BEAM_POOL
      - BEAM_USER
    command: miner --algo beamhash --server $BEAM_POOL --user $BEAM_USER.$WORKER

  chia:
    <<: *app
    entrypoint: ./chia_entrypoint.sh
    working_dir: /chia-blockchain
    volumes:
      - ./chia_entrypoint.sh:/chia-blockchain/chia_entrypoint.sh
      - ./chia_keys:/chia_keys
      - ./mkplots.sh:/chia-blockchain/mkplots.sh
      - ./farmer.sh:/chia-blockchain/farmer.sh
      - $PLOTS:/plots
      - $TMP_PLOTS:/tmp_plots
    command: ./farmer.sh
    environment:
      - WORKER

  plotter:
    <<: *app
    working_dir: /chia-plotter
    volumes:
      - $PLOTS:/plots
      - $TMP_PLOTS:/tmp_plots

    command: ./chia-plotter-linux-amd64 -action plotting -plotting-fpk $CHIA_FPK -plotting-ppk $CHIA_PPK -t /tmp_plots -d /plots -plotting-n 1
    environment:
      - WORKER
      - CHIA_KEYS
      - CHIA_PPK
      - CHIA_PFK
