version: '2.4'

x-app: &app
    image: "${DOCKER_REGISTRY:-localhost}/mine/mine"
    build:
      context: .
    shm_size: '30gb'
    runtime: nvidia


services:
  eth:
    <<: *app
    environment:
      - WORKER
      - ETH_POOL
      - ETH_USER
    command: miner --algo ethash --ssl 1 --server $ETH_POOL --user $ETH_USER.$WORKER

  rvn:
    <<: *app
    environment:
      - WORKER
      - RVN_POOL
      - RVN_USER
    command: miner --algo kawpow --server $RVN_POOL --user $RVN_USER.$WORKER

  chia:
    <<: *app
    entrypoint: ./chia_entrypoint.sh
    working_dir: /chia-blockchain
    volumes:
      - ./chia_entrypoint.sh:/chia-blockchain/chia_entrypoint.sh
      - ./mkplots.sh:/chia-blockchain/mkplots.sh
      - ./farmer.sh:/chia-blockchain/farmer.sh
      - ./mainnet:/root/.chia/mainnet
      - $MNT:/mnt
      - $TMP_PLOTS:/tmp_plots
    command: ./farmer.sh
    environment:
      - WORKER
      - CHIA_KEY
      - P2_SINGLETOM_ADDRESS
      - PLOTS
