version: '3.8'
x-environment: &environment
  MNT: &MNT ${MNT:-/mnt}
  CHIA_MAINNET: &CHIA_MAINNET ${CHIA_MAINNET:-./mainnet}
  TMP_PLOTS: &TMP_PLOTS ${TMP_PLOTS:-/tmp/plots}
  WORKER: &WORKER ${WORKER:-minemine}
  CHIA_KEY: &CHIA_KEY ${CHIA_KEY}
  CHIA_POOL_KEY: &CHIA_POOL_KEY ${CHIA_POOL_KEY}
  CHIA_POOL_CONTRACT_ADDRESS: &CHIA_POOL_CONTRACT_ADDRESS ${CHIA_POOL_CONTRACT_ADDRESS}
  NVIDIA_VISIBLE_DEVICES: &NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}
  RVN_POOL: &RVN_POOL ${RVN_POOL:-rvn.hiveon.com:8888}
  RVN_USER: &RVN_USER ${RVN_USER}
  ERGO_POOL: &ERGO_POOL ${ERGO_POOL:-asia-erg.2miners.com:8888}
  ERGO_USER: &ERGO_USER ${ERGO_USER}


x-app: &app
    image: "${DOCKER_REGISTRY:-localhost}/mine/mine"
    build:
      context: .
    environment:
      <<: *environment
    shm_size: '30gb'


services:
  etc:
    <<: *app
    runtime: nvidia
    environment:
      - WORKER
      - ETC_POOL
      - ETC_USER
    command: lolMiner  --algo ETCHASH  --pool $ETC_POOL --user $ETC_USER.$WORKER

  rvn:
    <<: *app
    runtime: nvidia
    command: lolMiner --algo kawpow --server $RVN_POOL --user $RVN_USER.$WORKER 

  ergo:
    <<: *app
    runtime: nvidia
    command: lolMiner --algo AUTOLYKOS2 --pool $ERGO_POOL --user $ERGO_USER.$WORKER 

  chia:
    <<: *app
    entrypoint: ./chia_entrypoint.sh
    working_dir: /chia-blockchain
    volumes:
      - type: bind
        source: ./chia_entrypoint.sh
        target: /chia-blockchain/chia_entrypoint.sh
      - type: bind
        source: ./mkplots.sh
        target: /chia-blockchain/mkplots.sh
      - type: bind
        source: ./farmer.sh
        target: /chia-blockchain/farmer.sh
      - type: bind
        source: *CHIA_MAINNET
        target: /root/.chia/mainnet
      - type: bind
        source: *MNT
        target: /mnt
    command: ./farmer.sh
    ports:
      - 8444:8444
