version: '2.4'

x-app: &app
    image: "${DOCKER_REGISTRY}/mine/mine"
    build:
      context: .
    shm_size: '30gb'
    runtime: nvidia
    restart: always


services:
  eth:
    <<: *app
    environment:
      - WORKER
      - ETH_POOL
      - ETH_USER
    command: miner --algo ethash --server $ETH_POOL --user $ETH_USER.$WORKER

  chia:
    <<: *app
    entrypoint: ./chia_entrypoint.sh
    working_dir: /chia-blockchain
    volumes:
      - ./chia_entrypoint.sh:/chia-blockchain/chia_entrypoint.sh
      - ./mkplots.sh:/chia-blockchain/mkplots.sh
      - ./farmer.sh:/chia-blockchain/farmer.sh
      - $PLOTS:/plots
      - $TMP_PLOTS:/tmp_plots
    command: ./farmer.sh
    environment:
      - WORKER
      - CHIA_KEY

  chia-miner:
    <<: *app
    working_dir: /chia-miner
    volumes:
      - $MNT:/mnt
      - ./chia-config.yaml:/chia-miner/config.yaml
    command: ./AzPool-Chia-Miner
    environment:
      - WORKER

  # rvn:
  #   <<: *app
  #   environment:
  #     - WORKER
  #     - RVN_POOL
  #     - RVN_USER
  #   command: miner --algo kawpow --server $RVN_POOL --user $RVN_USER.$WORKER

  # beam:
  #   <<: *app
  #   environment:
  #     - WORKER
  #     - BEAM_POOL
  #     - BEAM_USER
  #   command: miner --algo beamhash --server $BEAM_POOL --user $BEAM_USER.$WORKER

