version: '3.8'
x-environment: &environment
  MNT: &MNT ${MNT:-/mnt}
  CHIA_MAINNET: &CHIA_MAINNET ${CHIA_MAINNET:-./mainnet}
  TMP_PLOTS: &TMP_PLOTS ${TMP_PLOTS:-/tmp/plots}
  WORKER: &WORKER ${WORKER:-minemine}
  CHIA_KEY: &CHIA_KEY ${CHIA_KEY}
  CHIA_POOL_KEY: &CHIA_POOL_KEY ${CHIA_POOL_KEY}
  CHIA_POOL_CONTRACT_ADDRESS: &CHIA_POOL_CONTRACT_ADDRESS ${CHIA_POOL_CONTRACT_ADDRESS}
  NVIDIA_VISIBLE_DEVICES: &NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}

x-app: &app
    image: "${DOCKER_REGISTRY:-localhost}/mine/mine"
    build:
      context: .
    environment:
      <<: *environment
    shm_size: '30gb'


services:
  eth:
    <<: *app
    runtime: nvidia
    environment:
      - WORKER
      - ETH_POOL
      - ETH_USER
    command: miner  --algo ethash --ssl 1 --server $ETH_POOL --user $ETH_USER.$WORKER

  etc:
    <<: *app
    runtime: nvidia
    environment:
      - WORKER
      - ETC_POOL
      - ETC_USER
    command: miner  --algo etchash --ssl 1 --server $ETC_POOL --user $ETC_USER.$WORKER

  rvn:
    <<: *app
    runtime: nvidia
    environment:
      - WORKER
      - RVN_POOL
      - RVN_USER
    command: miner --algo kawpow --server $RVN_POOL --user $RVN_USER.$WORKER 

  ergo:
    <<: *app
    runtime: nvidia
    environment:
      - WORKER
      - ERGO_POOL
      - ERGO_USER
    command: lolMiner --algo AUTOLYKOS2 --pool $ERGO_POOL --user $ERGO_USER.$WORKER 

  chia:
    <<: *app
    entrypoint: ./chia_entrypoint.sh
    working_dir: /chia-blockchain
    volumes:
      - type: build
        source: ./chia_entrypoint.sh
        target: /chia-blockchain/chia_entrypoint.sh
      - type: build
        source: ./mkplots.sh
        target: /chia-blockchain/mkplots.sh
      - type: build
        source: ./farmer.sh
        target: /chia-blockchain/farmer.sh
      - type: bind
        source: *CHIA_MAINNET
        target: /root/.chia/mainnet
      - type: bind
        source: *MNT
        target: /mnt
    command: ./farmer.sh
    ports:
      - 8444:8444
